name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2
  firebase_core: ^2.4.0
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  google_sign_in_web: ^0.12.4
  awesome_dialog: ^3.2.0
  form_field_validator: ^1.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # assets:
  #   # - assets/images/1000_F_460710131_YkD6NsivdyYsHupNvO3Y8MPEwxTAhORh.jpg
  uses-material-design: true
